import 'package:flutter/material.dart';
import '../../../core/config/app_environment.dart';
import '../../../core/errors/app_exception.dart';
import '../data/money_api.dart';
class MoneyPage extends StatefulWidget{const MoneyPage({required this.accessToken,super.key});final String accessToken;@override State<MoneyPage> createState()=>_MoneyPageState();}
class _MoneyPageState extends State<MoneyPage>{
 late final MoneyApi api;List<MoneyTransaction> tx=[];List<MoneyAccount> accounts=[];List<MoneyCategory> categories=[];bool loading=true;String? error;
 @override void initState(){super.initState();api=MoneyApi(config:AppEnvironmentConfig.development);load();}
 Future<void> load()async{if(!mounted)return;setState((){loading=true;error=null;});try{final r=await Future.wait([api.list(widget.accessToken),api.accounts(widget.accessToken),api.categories(widget.accessToken)]);if(mounted)setState((){tx=r[0] as List<MoneyTransaction>;accounts=r[1] as List<MoneyAccount>;categories=r[2] as List<MoneyCategory>;});}catch(e){if(mounted)setState(()=>error=e is AppException?e.message:'Unable to load money.');}finally{if(mounted)setState(()=>loading=false);}}
 void msg(String s){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));}
 Future<void> form([MoneyTransaction? old])async{
  if(accounts.isEmpty){msg('Add an account first.');return;}final amount=TextEditingController(text:old==null?'':old.amount.toStringAsFixed(2));final desc=TextEditingController(text:old?.description??'');
  var type=old?.type??'EXPENSE',account=old?.accountId??accounts.first.id,category=old?.categoryId,destination=old?.transferAccountId,date=old?.date??DateTime.now();
  final ok=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,showDragHandle:true,builder:(c)=>StatefulBuilder(builder:(c,set)=>Padding(padding:EdgeInsets.fromLTRB(20,10,20,MediaQuery.viewInsetsOf(c).bottom+20),child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[
   Text(old==null?'Add money entry':'Edit money entry',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:12),
   SegmentedButton<String>(segments:const[ButtonSegment(value:'EXPENSE',label:Text('Expense')),ButtonSegment(value:'INCOME',label:Text('Income')),ButtonSegment(value:'REFUND',label:Text('Refund')),ButtonSegment(value:'TRANSFER',label:Text('Transfer'))],selected:{type},onSelectionChanged:(v)=>set(()=>type=v.first)),
   const SizedBox(height:10),DropdownButtonFormField<int>(initialValue:account,decoration:const InputDecoration(labelText:'Account'),items:accounts.map((a)=>DropdownMenuItem(value:a.id,child:Text(a.name))).toList(),onChanged:(v)=>set(()=>account=v!)),
   if(type=='TRANSFER')...[
    const SizedBox(height:10),DropdownButtonFormField<int>(initialValue:destination,decoration:const InputDecoration(labelText:'To account'),items:accounts.where((a)=>a.id!=account).map((a)=>DropdownMenuItem(value:a.id,child:Text(a.name))).toList(),onChanged:(v)=>set(()=>destination=v))
   ]else...[
    const SizedBox(height:10),DropdownButtonFormField<int>(initialValue:category,decoration:const InputDecoration(labelText:'Category (optional)'),items:categories.where((x)=>x.type==type||(type=='REFUND'&&x.type=='INCOME')).map((x)=>DropdownMenuItem(value:x.id,child:Text(x.name))).toList(),onChanged:(v)=>set(()=>category=v))
   ],
   const SizedBox(height:10),TextField(controller:amount,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount',prefixText:'₹ ')),
   const SizedBox(height:10),TextField(controller:desc,decoration:const InputDecoration(labelText:'Description'),maxLines:2),
   ListTile(contentPadding:EdgeInsets.zero,title:const Text('Date'),subtitle:Text(date.day.toString().padLeft(2,'0')+'/'+date.month.toString().padLeft(2,'0')+'/'+date.year.toString()),trailing:const Icon(Icons.calendar_today),onTap:()async{final d=await showDatePicker(context:c,initialDate:date,firstDate:DateTime(2020),lastDate:DateTime(2100));if(d!=null)set(()=>date=DateTime(d.year,d.month,d.day,date.hour,date.minute));}),
   const SizedBox(height:8),FilledButton(onPressed:()async{final value=double.tryParse(amount.text);if(value==null||value<=0){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Enter a valid amount.')));return;}if(type=='TRANSFER'&&(destination==null||destination==account)){ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Choose a different destination account.')));return;}try{final categoryId=type=='TRANSFER'?null:category;final transferId=type=='TRANSFER'?destination:null;if(old==null){await api.create(widget.accessToken,accountId:account,categoryId:categoryId,transferAccountId:transferId,type:type,amount:value,description:desc.text.trim().isEmpty?null:desc.text.trim(),date:date);}else{await api.update(widget.accessToken,old.id,accountId:account,categoryId:categoryId,transferAccountId:transferId,type:type,amount:value,description:desc.text.trim().isEmpty?null:desc.text.trim(),date:date);}if(c.mounted)Navigator.pop(c,true);}catch(e){ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e is AppException?e.message:'Unable to save entry.')));}},child:Text(old==null?'Add entry':'Save changes')),const SizedBox(height:8)
  ])))));
  amount.dispose();desc.dispose();if(ok==true)await load();
 }
 Future<void> remove(MoneyTransaction t)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Remove entry?'),content:const Text('This transaction will be deactivated.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Remove'))]));if(ok==true)try{await api.remove(widget.accessToken,t.id);await load();}catch(e){msg(e is AppException?e.message:'Unable to remove entry.');}}
 @override Widget build(BuildContext c)=>Scaffold(body:RefreshIndicator(onRefresh:load,child:ListView(physics:const AlwaysScrollableScrollPhysics(),padding:const EdgeInsets.fromLTRB(20,18,20,100),children:[
  Text('Money',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:6),const Text('Income, expenses, refunds and transfers'),const SizedBox(height:16),
  if(loading&&tx.isEmpty)const Center(child:CircularProgressIndicator())else if(error!=null&&tx.isEmpty)Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[Text(error!,textAlign:TextAlign.center),const SizedBox(height:12),FilledButton.icon(onPressed:load,icon:const Icon(Icons.refresh),label:const Text('Retry'))])))else if(tx.isEmpty)Card(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[const Icon(Icons.receipt_long_outlined,size:48),const SizedBox(height:10),Text('No money entries yet',style:Theme.of(c).textTheme.titleLarge),const SizedBox(height:8),const Text('Record your first expense or income.',textAlign:TextAlign.center),const SizedBox(height:12),FilledButton.icon(onPressed:()=>form(),icon:const Icon(Icons.add),label:const Text('Add entry'))])))else...tx.map(_tile)
 ])),floatingActionButton:FloatingActionButton.extended(onPressed:()=>form(),icon:const Icon(Icons.add),label:const Text('Add entry')));
 Widget _tile(MoneyTransaction t){final incoming=t.type=='INCOME'||t.type=='REFUND';final account=accounts.where((a)=>a.id==t.accountId).firstOrNull?.name??'Account';return Card(child:ListTile(leading:CircleAvatar(child:Icon(t.type=='TRANSFER'?Icons.swap_horiz:incoming?Icons.arrow_downward:Icons.arrow_upward)),title:Text(t.description.isEmpty?t.type:t.description),subtitle:Text(t.type+' • '+account+' • '+t.date.day.toString().padLeft(2,'0')+'/'+t.date.month.toString().padLeft(2,'0')+'/'+t.date.year.toString()),trailing:PopupMenuButton<String>(onSelected:(v)=>v=='edit'?form(t):remove(t),itemBuilder:(_)=>const[PopupMenuItem(value:'edit',child:Text('Edit')),PopupMenuItem(value:'remove',child:Text('Remove'))])));}
}