import 'package:flutter/material.dart';
import '../../accounts/presentation/accounts_page.dart';
import '../../auth/data/auth_repository.dart';
import '../../dashboard/presentation/dashboard_page.dart';
import '../../credit/presentation/credit_page.dart';
import '../../lending/presentation/lending_page.dart';
import '../../money/presentation/money_page.dart';
import '../../profile/presentation/profile_page.dart';
class AppShell extends StatefulWidget{const AppShell({required this.repository,required this.accessToken,required this.email,required this.onLogout,super.key});final AuthRepository repository;final String accessToken,email;final Future<void> Function() onLogout;@override State<AppShell> createState()=>_AppShellState();}
class _AppShellState extends State<AppShell>{int index=0;late List<Widget> pages;@override void initState(){super.initState();pages=_pages();}@override void didUpdateWidget(covariant AppShell old){super.didUpdateWidget(old);if(old.accessToken!=widget.accessToken||old.email!=widget.email)pages=_pages();}List<Widget> _pages()=>[DashboardPage(key:const PageStorageKey('dashboard'),accessToken:widget.accessToken),MoneyPage(key:const PageStorageKey('money'),accessToken:widget.accessToken),AccountsPage(key:const PageStorageKey('accounts'),accessToken:widget.accessToken),CreditPage(key:const PageStorageKey('credit'),accessToken:widget.accessToken),LendingPage(key:const PageStorageKey('lending'),accessToken:widget.accessToken),ProfilePage(key:const PageStorageKey('profile'),repository:widget.repository,initialEmail:widget.email,onLogout:widget.onLogout)];
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Money Maintainer'),actions:[if(index!=5)IconButton(onPressed:()=>setState(()=>index=5),icon:const Icon(Icons.person_outline))]),body:IndexedStack(index:index,children:pages),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:[const NavigationDestination(icon:Icon(Icons.dashboard_outlined),selectedIcon:Icon(Icons.dashboard),label:'Home'),const NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'Money'),const NavigationDestination(icon:Icon(Icons.account_balance_wallet_outlined),selectedIcon:Icon(Icons.account_balance_wallet),label:'Accounts'),const NavigationDestination(icon:Icon(Icons.credit_card_outlined),selectedIcon:Icon(Icons.credit_card),label:'Credit'),const NavigationDestination(icon:Icon(Icons.handshake_outlined),selectedIcon:Icon(Icons.handshake),label:'Lending'),const NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')]) );}
